import { Navbar } from "../ui/Navbar"
import Head from "next/head"
import styles from "../../styles/Home.module.css"


export const Layout = ({children, title = "Miguel Dev"}) => {

    return(
        <div className={styles.body}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.svg" />
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
                <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;700&display=swap" rel="stylesheet"/>
            </Head>
            <Navbar/>
            {children}
        </div>
    )

}

