import { Navbar } from "../ui/Navbar"
import Head from "next/head"


export const Layout = ({children, title = "Miguel Dev"}) => {

    return(
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.svg" />
            </Head>
            <Navbar/>
            {children}
        </>
    )

}

